# Site
name: "Remembering Greenville: Longtown History Harvest"
title: "Remembering Greenville: Longtown History Harvest"
description: ""
meta_description: "Remembering Greenville: Longtown History Harvest"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: ''
include: ["_pages"]
permalink: /:title/

    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  contributors:
    output: true
    permalink: /:collection/:path:output_ext
    name: true
    folder: true
    sort_by: folder
  items:
    output: true
    permalink: /:collection/:path:output_ext
    itemcontributor: true
    itemgroupid: true
    itemgroupname: true
    itemid: true
