# Site
title: "Remembering Freedom"
subtitle: "Longtown and Greenville History Harvest"
description: "Remembering Freedom: Longtown and Greenville History Harvest"
meta_description: "Remembering Freedom: Longtown and Greenville History Harvest"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: ''
include: ["_pages"]
permalink: /:title/

    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  descendants:
    output: true
    permalink: /:collection/:path:output_ext
    name: true
    folder: true
    sort_by: folder
  items:
    output: true
    permalink: /:collection/:path:output_ext
    itemdescendant: true
    itemgroupid: true
    itemgroupname: true
    itemid: true
  oralhistories:
    output: true
    permalink: /:collection/:path:output_ext
    name: true
    folder: true
    sort_by: folder
  tours:
    output: true
    permalink: /:collection/:path:output_ext
    name: true
    folder: true
    sort_by: building
